version: '3.9'

services:
  app:
    image: 'springio/testtask:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - postgres

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/task-manager
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "task-manager"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_ROOT_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./init_db/db.sql:/init_db/db.sql
      - task-manager-data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    expose:
      - "5435"
volumes:
  task-manager-data: