create table if not exists tag
(
    id    bigint generated by default as identity
        primary key,
    title varchar(255)
);

alter table tag
    owner to postgres;

create table if not exists type
(
    id    bigint generated by default as identity
        primary key,
    level integer,
    title varchar(255)
);

alter table type
    owner to postgres;

create table if not exists task
(
    id          bigint generated by default as identity
        primary key,
    description varchar(255),
    name        varchar(255),
    task_date   date,
    uid_tag     bigint not null
        constraint fk_task_taguid
            references tag,
    uid_type    bigint not null
        constraint fk_task_typeuid
            references type

);

alter table task
    owner to postgres;

-- тестовые начальные данные
INSERT INTO tag(title)
VALUES ('Backend'),
       ('Frontend'),
       ('Design');

INSERT INTO type(title, level)
VALUES ('обычная', 40),
       ('важная', 60),
       ('срочная', 90),
       ('по возможности', 0);